name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install PyGithub

    - name: Parse commit message and update README
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python update_readme.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'hwangbo98'
        git config --global user.email 'hwangbo1998@gmail.com'
        git add README.md
        git commit -m 'Update README with new problem'
        git push
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
